name: Verify with Maven

on:
  pull_request:
    branches:
      - '**'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: mvn clean verify -DlatestOnly=true
