name: Deploy with Maven

on:
  release:
    types: [ created ]
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME_TOKEN
          server-password: MAVEN_CENTRAL_PASSWORD_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Deploy with Maven
        run: mvn -B clean deploy -DskipTests
        env:
          MAVEN_CENTRAL_USERNAME_TOKEN: ${{ secrets.MAVEN_CENTRAL_USERNAME_TOKEN }}
          MAVEN_CENTRAL_PASSWORD_TOKEN: ${{ secrets.MAVEN_CENTRAL_PASSWORD_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          